### ISSUE TITLE
Create versioned release bundles

### ISSUE THREAD

**Issue by mcorner** [GoogleCloudPlatform/recaptcha-enterprise-google-tag-manager#3]
We need to add versioning to the release bundles and send the version to create assessment (when that endpoint supports it).

**Comment by blackwire** [comment]
@mcorner - If it is added before the endpoint supports it will the endpoint simply ignore the parameter or will we get a 400?

**Comment by mcorner** [comment]
We can wait, it will be out very soon (internal ref: b/351141650)
